trigger:
  branches:
    include:
      - main
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node 20.x'
  inputs:
    versionSpec: '20.x'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: .
    verbose: false

- task: Npm@1
  displayName: 'build extension'
  inputs:
    command: custom
    workingDir: .
    verbose: false
    customCommand: 'run build:cidev'

- task: TfxInstaller@1
  displayName: 'Install tfx-cli'
  inputs:
    version: '0.x'

- task: PackageAzureDevOpsExtension@5
  displayName: 'TFX: Package Extension Prod'
  inputs:
    rootFolder: .
    patternManifest: 'azure-devops-extension.json'
    publisherId: nsierraj
    extensionId: azure-pipelines-html-report
    extensionName: 'Html Viewer'
    extensionVisibility: public
    extensionPricing: free
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))

- task: PackageAzureDevOpsExtension@5
  displayName: 'TFX: Package Extension Dev'
  inputs:
    rootFolder: .
    patternManifest: 'azure-devops-extension.json'
    publisherId: nsierraj
    extensionId: azure-pipelines-html-report
    extensionTag: dev
    extensionName: 'Html Viewer Dev'
    extensionVersion: '1.0.$(Build.BuildId)'
    updateTasksVersion: true
    extensionVisibility: private
    extensionPricing: free
  condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'main'))

- task: PublishAzureDevOpsExtension@5
  displayName: 'TFX: Publish Extension Dev'
  inputs:
    connectedServiceName: nsierrajMarketPlace
    rootFolder: .
    patternManifest: 'azure-devops-extension.json'
    publisherId: nsierraj
    extensionId: azure-pipelines-html-report
    extensionTag: dev
    extensionName: 'Html Viewer Dev'
    extensionVersion: '1.0.$(Build.BuildId)'
    extensionVisibility: private
    extensionPricing: free
  condition: and(succeeded(), ne(variables['Build.SourceBranchName'], 'main'))

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/results'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/results'
  condition: succeededOrFailed()
